services:
  statletics-frontend:
    build:
      context: ./statletics-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - statletics-backend

  statletics-backend:
    build:
      context: ./statletics-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: results_swiss_athletics
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data:
