name: build, test and deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container : node:22
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '22'
      - run: npm ci 
      #- run: npm run lint --prefix statletics-frontend
      - run: npm run build

