name: build, test and deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and build frontend
        working-directory: statletics-frontend
        run: |
          npm ci
          npm run build

