name: Build, Test and Deploy

on:
  push:
    branches: ["main"]

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy application using temporary SSH key file
        run: |
          echo -e "${{ secrets.SSH_KEY }}" > __TEMP_INPUT_KEY_FILE
          chmod 600 __TEMP_INPUT_KEY_FILE
          # Nettoie le dossier distant
          ssh -o StrictHostKeyChecking=no -i __TEMP_INPUT_KEY_FILE -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" "rm -rf /home/timnuc/Documents/statleticsv2/statletics/*"
          # Transfert l'ensemble des fichiers vers le dossier de déploiement
          scp -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE -P "${{ secrets.SSH_PORT }}" -r . "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}":"/home/timnuc/Documents/statleticsv2/statletics"
          # Lance la mise à jour des containers via Docker Compose
          ssh -o StrictHostKeyChecking=no -i __TEMP_INPUT_KEY_FILE -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" "cd /home/timnuc/Documents/statleticsv2/statletics && docker compose pull && docker compose down && docker compose up -d --build"
          rm __TEMP_INPUT_KEY_FILE

